apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1-karunnyi-ambulance-ufe-content
spec:
  microFrontend: cv1-karunnyi-ambulance-ufe
  element: cv1karunnyi-ambulance-ufe-router
  attributes:
    - name: base-path
      value: /cv1karunnyi-ambulance-ufe/
    - name: api-base
      value: /cv1karunnyi-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1-karunnyi-ambulance-ufe(/.*)?$"