apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1-karunnyi-ambulance-ufe-content
spec:
  microFrontend: cv1-karunnyi-ambulance-ufe
  element: cv1karunnyi-ambulance-ufe-track
  attributes:
    - name: api-base
      value: http://localhost:30081/api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1-karunnyi-ambulance-ufe(/.*)?$"