apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: kxrunnyi/ambulance-wl-webapi
    newName: kxrunnyi/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main.20250611.0008 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
  - name: kxrunnyi/cv-ambulance-ufe
    newName: kxrunnyi/cv-ambulance-ufe # {"$imagepolicy":  "wac-hospital:cv-ambulance-ufe:name"}
    newTag: main.20250611.0034 # {"$imagepolicy": "wac-hospital:cv-ambulance-ufe:tag"}
